Repository CS3219-AY2425S1/cs3219-ay2425s1-project-g35, pull requests merged in 2024-10, with the labels that each got.

#14 User service docker
  UserService/.gitignore
  UserService/Dockerfile
  UserService/README.md
  UserService/user-service/.env.sample
  UserService/user-service/GuideAssets/AddIPAddress.png
  UserService/user-service/GuideAssets/ConnectCluster.png
  UserService/user-service/GuideAssets/ConnectionString.png
  UserService/user-service/GuideAssets/Creation.png
  UserService/user-service/GuideAssets/DriverSelection.png
  UserService/user-service/GuideAssets/IPWhitelisting.png
  UserService/user-service/GuideAssets/Network.png
  UserService/user-service/GuideAssets/Security.png
  UserService/user-service/GuideAssets/Selection.png
  UserService/user-service/GuideAssets/Selection1.png
  UserService/user-service/GuideAssets/Selection2.png
  UserService/user-service/GuideAssets/Selection3.png
  UserService/user-service/GuideAssets/Selection4.png
  UserService/user-service/GuideAssets/SidePane.png
  UserService/user-service/MongoDBSetup.md
  UserService/user-service/README.md
  UserService/user-service/controller/auth-controller.js
  UserService/user-service/controller/user-controller.js
  UserService/user-service/index.js
  UserService/user-service/middleware/basic-access-control.js
  UserService/user-service/model/repository.js
  UserService/user-service/model/user-model.js
  UserService/user-service/package-lock.json
  UserService/user-service/package.json
  UserService/user-service/routes/auth-routes.js
  UserService/user-service/routes/user-routes.js
  UserService/user-service/server.js
  docker-compose.yaml
  frontend/.gitignore
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.css
  frontend/src/App.jsx
  frontend/src/components/Navbar.jsx
  frontend/src/components/Navbar/Navbar.jsx
  frontend/src/components/Navbar/Navbar.module.css
  frontend/src/components/ProtectedRoute/ProtectedRoute.jsx
  frontend/src/components/QuestionTable.jsx
  frontend/src/hooks/useLogin.jsx
  frontend/src/hooks/useLogout.jsx
  frontend/src/hooks/useQuestionTable.jsx
  frontend/src/hooks/useRegister.jsx
  frontend/src/views/login-page/LoginPage.jsx
  frontend/src/views/login-page/LoginPage.module.css
  frontend/src/views/main-page/MainPage.css
  frontend/src/views/main-page/MainPage.jsx
  frontend/src/views/register-page/RegisterPage.jsx
  frontend/src/views/register-page/RegisterPage.module.css
  package-lock.json
  package.json
Labels: enhancement

#24 Fix user login cookies and Ui enhancements
  .gitignore
  frontend/src/components/Navbar/Navbar.jsx
  frontend/src/components/Navbar/Navbar.module.css
  frontend/src/hooks/useLogin.jsx
  frontend/src/views/login-page/LoginPage.jsx
  frontend/src/views/login-page/LoginPage.module.css
  frontend/src/views/register-page/RegisterPage.jsx
  frontend/src/views/register-page/RegisterPage.module.css
Labels: bug, enhancement

#37 Frontend matching fix
  MatchingService/services/matchService.js
  frontend/src/hooks/useMatcher.jsx
  frontend/src/views/matching-page/MatchingPage.jsx
Labels: bug
